---
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
  myAZ: 
    Description: Select Availability Zone
    Type: AWS::EC2::AvailabilityZone::Name
  myImageId:
    Type: String
    Default: ami-0742b4e673072066f
    AllowedValues:
      - ami-0742b4e673072066f
      - ami-042e8287309f5df03
      - ami-013f17f36f8b1fefb
Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Ref: InstanceTypeParameter
      AvailabilityZone: 
        Ref: myAZ
      ImageId: 
        Ref: myImageId
      KeyName:
        Ref: myKeyPair